### ISSUE TITLE
Full User checklist

### ISSUE THREAD

**Issue by Lillith13** [Lillith13/CannaCafe#13]
- [x] Create an account (signUp)
- [x] Log in and log out functionality
- [x] Delete account capability (in profile) - For members only to delete their own, Employees + only gain this ability once they've been downgraded back to a Member
- [x] Edit account capability (in profile)
- [x] Employee accounts & hours tracking
	* Employee accounts are only able to be created by management - promotion an demotion abilities only accessible by someone higher ranking than themselves

**Comment by Lillith13** [comment]
For double-checking desired functionality:
Current full cruds => Reviews and Products
Current partial cruds => Profile, MerchOrders, DeliveryOrders, Wishlist, Favorites
